#!/usr/bin/env python3
"""
Analyze test tone recordings from the TBD-16 Doom audio pipeline.

Usage:
    python analyze_test_tones.py <recording.wav|recording.m4a>

The recording should contain the test tone sequence generated by
AUDIO_TEST_TONES=1 in platformio.ini.  The script:

1. Finds the sync pattern (3× 2 kHz beeps)
2. Segments the recording by known phase timing
3. Analyzes each segment for frequency accuracy, amplitude, THD,
   noise floor, aliasing, and clipping
4. Prints a diagnostic report with PASS/FAIL verdicts

Test tone sequence (generated at 49716 Hz on RP2350):
  0: SYNC — 3× 100 ms beep at 2 kHz           (600 ms)
  1: SILENCE                                    (2 s)
  2: 1 kHz sine at -30 dBFS                     (2 s)
  3: 1 kHz sine at -24 dBFS                     (2 s)
  4: 1 kHz sine at -18 dBFS (edge of clipping)  (2 s)
  5: 1 kHz sine at -12 dBFS (clipped by ×8)     (2 s)
  6: 440 Hz sine at -24 dBFS                    (2 s)
  7: Log sweep 100 Hz → 20 kHz at -24 dBFS      (4 s)
  8: 1 kHz square wave at -24 dBFS              (2 s)
  9: 19 kHz + 20 kHz at -30 dBFS each (IMD)     (2 s)
 10: Impulse train 200 Hz at -24 dBFS            (2 s)
"""

import sys
import os
import subprocess
import struct
import wave

import numpy as np
from scipy import signal
from scipy.fft import rfft, rfftfreq

# ── Phase definitions (must match i_picosound.c) ────────────────────

PHASES = [
    {"name": "SYNC",              "dur_s": 1.0,  "freq": 2000, "amp_dbfs": None},
    {"name": "SILENCE",           "dur_s": 4.0,  "freq": None, "amp_dbfs": None},
    {"name": "1kHz -30dBFS",      "dur_s": 4.0,  "freq": 1000, "amp_dbfs": -30},
    {"name": "1kHz -24dBFS",      "dur_s": 4.0,  "freq": 1000, "amp_dbfs": -24},
    {"name": "1kHz -18dBFS",      "dur_s": 4.0,  "freq": 1000, "amp_dbfs": -18},
    {"name": "1kHz -12dBFS",      "dur_s": 4.0,  "freq": 1000, "amp_dbfs": -12},
    {"name": "440Hz -24dBFS",     "dur_s": 4.0,  "freq": 440,  "amp_dbfs": -24},
    {"name": "SWEEP 100-20kHz",   "dur_s": 8.0,  "freq": None, "amp_dbfs": -24},
    {"name": "SQUARE 1kHz",       "dur_s": 4.0,  "freq": 1000, "amp_dbfs": -24},
    {"name": "IMD 19k+20k",       "dur_s": 4.0,  "freq": None, "amp_dbfs": -30},
    {"name": "IMPULSE 200Hz",     "dur_s": 4.0,  "freq": 200,  "amp_dbfs": -24},
]

# P4 gain chain: int16 / 32768 × 8.0, clamped ±1.0
P4_GAIN = 8.0
CLIP_THRESHOLD_INT16 = 4096  # above this, P4 clips


def load_audio(path):
    """Load audio file.  Converts M4A to WAV via ffmpeg if needed."""
    if path.lower().endswith(('.m4a', '.aifc', '.aif', '.aiff')):
        wav_path = path.rsplit('.', 1)[0] + '_converted.wav'
        if not os.path.exists(wav_path):
            print(f"Converting {path} → {wav_path} via ffmpeg...")
            subprocess.run(
                ['ffmpeg', '-y', '-i', path, '-acodec', 'pcm_s16le',
                 wav_path],
                check=True, capture_output=True)
        path = wav_path

    with wave.open(path, 'rb') as wf:
        sr = wf.getframerate()
        nch = wf.getnchannels()
        nframes = wf.getnframes()
        raw = wf.readframes(nframes)

    fmt = f'<{nframes * nch}h'
    data = np.array(struct.unpack(fmt, raw), dtype=np.float64).reshape(-1, nch)

    # If multi-channel (e.g. TDM capture), extract first 2 channels
    if nch > 2:
        print(f"  Multi-channel recording ({nch} ch) — using channels 0+1")
        data = data[:, :2]

    return data, sr


def find_sync(mono, sr):
    """Find the start of the 3-beep sync pattern at 2 kHz."""
    # Bandpass around 2 kHz
    sos = signal.butter(4, [1800, 2200], btype='bandpass', fs=sr, output='sos')
    filtered = signal.sosfilt(sos, mono)
    envelope = np.abs(filtered)

    # Smooth with 10 ms window
    win = max(1, int(sr * 0.01))
    envelope = np.convolve(envelope, np.ones(win) / win, mode='same')

    # Dynamic threshold: find the strongest 2 kHz burst first
    peak_env = np.max(envelope)
    if peak_env < 10 / 32768:
        return None

    threshold = peak_env * 0.15
    above = envelope > threshold

    # Find rising edges
    edges = np.diff(above.astype(np.int8))
    rises = np.where(edges == 1)[0]

    if len(rises) == 0:
        return None

    # Look for 3 rises spaced ~200 ms apart (100ms on + 100ms off)
    for i in range(len(rises) - 2):
        d1 = (rises[i + 1] - rises[i]) / sr
        d2 = (rises[i + 2] - rises[i + 1]) / sr
        if 0.1 < d1 < 0.4 and 0.1 < d2 < 0.4:
            start = rises[i]
            while start > 0 and envelope[start] > threshold * 0.5:
                start -= 1
            return start

    # Fallback: use the first strong 2 kHz burst as sync start
    first_above = np.argmax(above)
    # Walk back to find the true start
    while first_above > 0 and envelope[first_above] > threshold * 0.3:
        first_above -= 1
    return first_above


def analyze_sine(mono_norm, sr, expected_freq, label):
    """Analyze a segment expected to contain a single sine tone."""
    n = len(mono_norm)
    # Use middle 80% to avoid edge transients
    margin = n // 10
    seg = mono_norm[margin:n - margin]
    n_seg = len(seg)

    # Peak and RMS
    peak = np.max(np.abs(seg))
    rms = np.sqrt(np.mean(seg ** 2))
    peak_dbfs = 20 * np.log10(peak + 1e-15)
    rms_dbfs = 20 * np.log10(rms + 1e-15)

    # FFT
    window = np.hanning(n_seg)
    spectrum = rfft(seg * window)
    freqs = rfftfreq(n_seg, 1 / sr)
    mag = np.abs(spectrum) * 2 / np.sum(window)

    # Find dominant frequency
    dominant_idx = np.argmax(mag[1:]) + 1
    dominant_freq = freqs[dominant_idx]

    # THD: ratio of harmonic power to fundamental power
    fund_idx = np.argmin(np.abs(freqs - expected_freq))
    fund_power = mag[fund_idx] ** 2
    harmonic_power = 0
    for h in range(2, 11):
        h_freq = expected_freq * h
        if h_freq > sr / 2:
            break
        h_idx = np.argmin(np.abs(freqs - h_freq))
        # Sum power in ±5 bin window
        lo = max(0, h_idx - 5)
        hi = min(len(mag), h_idx + 6)
        harmonic_power += np.max(mag[lo:hi]) ** 2

    thd_pct = np.sqrt(harmonic_power / (fund_power + 1e-20)) * 100

    # Noise floor: median of magnitude spectrum (dB)
    mag_db = 20 * np.log10(mag + 1e-15)
    noise_floor = np.median(mag_db)

    # Frequency error
    freq_error_hz = dominant_freq - expected_freq
    freq_error_pct = freq_error_hz / expected_freq * 100

    return {
        'label': label,
        'peak_dbfs': peak_dbfs,
        'rms_dbfs': rms_dbfs,
        'dominant_freq': dominant_freq,
        'freq_error_hz': freq_error_hz,
        'freq_error_pct': freq_error_pct,
        'thd_pct': thd_pct,
        'noise_floor_db': noise_floor,
    }


def analyze_silence(mono_norm, sr, label):
    """Analyze a segment expected to be silent."""
    n = len(mono_norm)
    margin = n // 10
    seg = mono_norm[margin:n - margin]

    peak = np.max(np.abs(seg))
    rms = np.sqrt(np.mean(seg ** 2))
    peak_dbfs = 20 * np.log10(peak + 1e-15)
    rms_dbfs = 20 * np.log10(rms + 1e-15)

    return {
        'label': label,
        'peak_dbfs': peak_dbfs,
        'rms_dbfs': rms_dbfs,
        'noise_floor_db': rms_dbfs,
    }


def analyze_sweep(mono_norm, sr, label):
    """Analyze the frequency sweep for frequency response."""
    n = len(mono_norm)
    # Split into ~50 ms windows and measure power in each
    win_samples = int(sr * 0.05)
    n_windows = n // win_samples

    freqs_measured = []
    powers = []
    for w in range(n_windows):
        start = w * win_samples
        seg = mono_norm[start:start + win_samples]
        window = np.hanning(len(seg))
        spectrum = rfft(seg * window)
        f = rfftfreq(len(seg), 1 / sr)
        mag = np.abs(spectrum) * 2 / np.sum(window)
        dominant_idx = np.argmax(mag[1:]) + 1
        freqs_measured.append(f[dominant_idx])
        powers.append(20 * np.log10(mag[dominant_idx] + 1e-15))

    freqs_measured = np.array(freqs_measured)
    powers = np.array(powers)

    # Find -3 dB point
    ref_power = np.max(powers[:len(powers) // 2])  # ref from low freq
    above_m3 = powers > (ref_power - 3)
    if np.any(~above_m3):
        first_drop = np.argmin(above_m3)
        bw_freq = freqs_measured[first_drop] if first_drop > 0 else freqs_measured[-1]
    else:
        bw_freq = freqs_measured[-1]

    # Power variation in 200-15000 Hz range
    mask = (freqs_measured > 200) & (freqs_measured < 15000)
    if np.any(mask):
        ripple = np.max(powers[mask]) - np.min(powers[mask])
    else:
        ripple = 0

    return {
        'label': label,
        'freqs': freqs_measured,
        'powers': powers,
        'bandwidth_m3db': bw_freq,
        'passband_ripple_db': ripple,
        'ref_power_db': ref_power,
    }


def analyze_square(mono_norm, sr, label):
    """Analyze square wave for harmonic content and ringing."""
    n = len(mono_norm)
    margin = n // 10
    seg = mono_norm[margin:n - margin]
    n_seg = len(seg)

    peak = np.max(np.abs(seg))
    rms = np.sqrt(np.mean(seg ** 2))

    # FFT
    window = np.hanning(n_seg)
    spectrum = rfft(seg * window)
    freqs = rfftfreq(n_seg, 1 / sr)
    mag = np.abs(spectrum) * 2 / np.sum(window)
    mag_db = 20 * np.log10(mag + 1e-15)

    # Ideal square wave has only odd harmonics: f, 3f, 5f, 7f...
    # Check presence of odd harmonics and absence of even
    fund_idx = np.argmin(np.abs(freqs - 1000))
    fund_mag = mag_db[fund_idx]

    odd_harmonics = []
    even_harmonics = []
    for h in range(2, 20):
        h_freq = 1000 * h
        if h_freq > sr / 2:
            break
        h_idx = np.argmin(np.abs(freqs - h_freq))
        lo = max(0, h_idx - 3)
        hi = min(len(mag_db), h_idx + 4)
        h_mag = np.max(mag_db[lo:hi])
        if h % 2 == 1:
            odd_harmonics.append((h, h_freq, h_mag))
        else:
            even_harmonics.append((h, h_freq, h_mag))

    return {
        'label': label,
        'peak_dbfs': 20 * np.log10(peak + 1e-15),
        'rms_dbfs': 20 * np.log10(rms + 1e-15),
        'fund_mag_db': fund_mag,
        'odd_harmonics': odd_harmonics,
        'even_harmonics': even_harmonics,
    }


def analyze_imd(mono_norm, sr, label):
    """Analyze intermodulation distortion of 19k+20k tone pair."""
    n = len(mono_norm)
    margin = n // 10
    seg = mono_norm[margin:n - margin]
    n_seg = len(seg)

    window = np.hanning(n_seg)
    spectrum = rfft(seg * window)
    freqs = rfftfreq(n_seg, 1 / sr)
    mag = np.abs(spectrum) * 2 / np.sum(window)
    mag_db = 20 * np.log10(mag + 1e-15)

    # Expected tones at 19 kHz and 20 kHz
    # After P4 resampling (49716→44100), these should be at:
    # 19000 Hz and 20000 Hz (if below Nyquist of recording)
    # IMD products: |f2-f1|=1kHz, |2f1-f2|=18kHz, |2f2-f1|=21kHz (aliased)

    results = {}
    for freq_name, freq_val in [('19kHz', 19000), ('20kHz', 20000),
                                 ('IMD 1kHz', 1000), ('IMD 18kHz', 18000)]:
        if freq_val > sr / 2:
            results[freq_name] = None
            continue
        idx = np.argmin(np.abs(freqs - freq_val))
        lo = max(0, idx - 5)
        hi = min(len(mag_db), idx + 6)
        results[freq_name] = np.max(mag_db[lo:hi])

    # Aliased frequencies: 49716 - 19000 = 30716 (above 22050, folds)
    # With AA filter at 20 kHz, should be suppressed
    # Check for alias at 44100 - 19000 = 25100 (if sr is 44100)
    alias_freq = sr - 19000
    if alias_freq < sr / 2 and alias_freq > 0:
        idx = np.argmin(np.abs(freqs - alias_freq))
        lo = max(0, idx - 5)
        hi = min(len(mag_db), idx + 6)
        results[f'alias {alias_freq:.0f}Hz'] = np.max(mag_db[lo:hi])

    results['noise_floor_db'] = np.median(mag_db)

    return {'label': label, 'tones': results}


def analyze_impulse(mono_norm, sr, label):
    """Analyze impulse response for transient behavior."""
    n = len(mono_norm)
    margin = n // 10
    seg = mono_norm[margin:n - margin]

    # Find impulse peaks
    threshold = np.max(np.abs(seg)) * 0.3
    peaks, props = signal.find_peaks(np.abs(seg), height=threshold,
                                      distance=int(sr / 300))

    if len(peaks) < 2:
        return {'label': label, 'error': 'Could not find impulse peaks'}

    # Measure impulse spacing (should be ~5 ms = 200 Hz)
    spacings = np.diff(peaks) / sr
    mean_spacing = np.mean(spacings)
    spacing_jitter = np.std(spacings)
    measured_rate = 1.0 / mean_spacing if mean_spacing > 0 else 0

    # Measure impulse width (how many samples above 10% of peak)
    peak_idx = peaks[len(peaks) // 2]  # use middle impulse
    peak_val = np.abs(seg[peak_idx])
    thresh_10pct = peak_val * 0.1
    width = 0
    for offset in range(-50, 51):
        if 0 <= peak_idx + offset < len(seg):
            if np.abs(seg[peak_idx + offset]) > thresh_10pct:
                width += 1

    return {
        'label': label,
        'n_impulses': len(peaks),
        'measured_rate_hz': measured_rate,
        'mean_spacing_ms': mean_spacing * 1000,
        'spacing_jitter_ms': spacing_jitter * 1000,
        'impulse_width_samples': width,
    }


def check_channel_match(data, sr):
    """Check if L and R channels match (should be identical mono)."""
    if data.shape[1] < 2:
        return None
    diff = data[:, 0] - data[:, 1]
    max_diff = np.max(np.abs(diff))
    rms_diff = np.sqrt(np.mean(diff ** 2))
    return {
        'max_diff': max_diff,
        'rms_diff': rms_diff,
        'max_diff_dbfs': 20 * np.log10(max_diff / 32768 + 1e-15),
    }


def print_header(title):
    print(f"\n{'═' * 70}")
    print(f"  {title}")
    print(f"{'═' * 70}")


def print_result(label, value, unit='', verdict=None):
    v_str = f"  [{verdict}]" if verdict else ""
    print(f"  {label:.<40s} {value:>10s} {unit:<6s}{v_str}")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <recording.wav|recording.m4a>")
        sys.exit(1)

    path = sys.argv[1]
    print(f"Loading {path}...")
    data, sr = load_audio(path)
    print(f"  Sample rate: {sr} Hz")
    print(f"  Channels: {data.shape[1]}")
    print(f"  Duration: {len(data) / sr:.1f} s")
    print(f"  Samples: {len(data)}")

    # Work with left channel, normalized to ±1.0
    mono = data[:, 0]
    mono_norm = mono / 32768.0

    # ── Find sync ──────────────────────────────────────────────────────
    print_header("SYNC DETECTION")
    sync_start = find_sync(mono_norm, sr)
    if sync_start is None:
        print("  ERROR: Could not find sync pattern!")
        print("  Make sure the recording contains the 3-beep sync.")
        sys.exit(1)

    sync_time = sync_start / sr
    print_result("Sync found at", f"{sync_time:.3f}", "s")

    # ── Segment the recording ──────────────────────────────────────────
    print_header("PHASE SEGMENTATION")
    segments = []
    pos = sync_start
    for phase in PHASES:
        dur_samples = int(phase['dur_s'] * sr)
        end = min(pos + dur_samples, len(mono_norm))
        segments.append({
            'start': pos,
            'end': end,
            'data': mono_norm[pos:end],
            'data_raw': data[pos:end],
            **phase,
        })
        t_start = pos / sr
        t_end = end / sr
        print(f"  {phase['name']:.<35s} {t_start:6.2f}s → {t_end:6.2f}s "
              f"({end - pos} samples)")
        pos = end

    # ── Channel matching ───────────────────────────────────────────────
    if data.shape[1] >= 2:
        print_header("CHANNEL MATCHING (L vs R)")
        ch = check_channel_match(data, sr)
        verdict = "PASS" if ch['max_diff'] < 2 else "WARN"
        print_result("Max L-R difference", f"{ch['max_diff']:.1f}", "int16", verdict)
        print_result("RMS L-R difference", f"{ch['rms_diff']:.2f}", "int16")

    # ── Analyze each phase ─────────────────────────────────────────────
    pass_count = 0
    fail_count = 0
    warn_count = 0

    def verdict(ok, label, val_str, unit='', warn=False):
        nonlocal pass_count, fail_count, warn_count
        if ok:
            pass_count += 1
            print_result(label, val_str, unit, "PASS")
        elif warn:
            warn_count += 1
            print_result(label, val_str, unit, "WARN")
        else:
            fail_count += 1
            print_result(label, val_str, unit, "FAIL")

    # Phase 1: SILENCE
    seg = segments[1]
    print_header(f"Phase 1: {seg['name']}")
    r = analyze_silence(seg['data'], sr, seg['name'])
    verdict(r['peak_dbfs'] < -50, "Noise floor (peak)",
            f"{r['peak_dbfs']:.1f}", "dBFS")
    verdict(r['rms_dbfs'] < -60, "Noise floor (RMS)",
            f"{r['rms_dbfs']:.1f}", "dBFS")

    # Phases 2-6: Sine tones at various levels
    # Expected output levels after P4 ×8 gain:
    expected_output = {
        2: (-30 + 18.06, False),   # -30 dBFS × 8 = -11.94 dBFS, no clip
        3: (-24 + 18.06, False),   # -24 dBFS × 8 = -5.94 dBFS, no clip
        4: (0.0, True),            # -18 dBFS × 8 ≈ 0 dBFS, edge clip
        5: (0.0, True),            # -12 dBFS × 8 → clipped, 0 dBFS peak
    }

    for idx in [2, 3, 4, 5]:
        seg = segments[idx]
        print_header(f"Phase {idx}: {seg['name']}")
        if len(seg['data']) < sr // 2:
            print("  SKIPPED (insufficient data — recording too short)")
            continue
        r = analyze_sine(seg['data'], sr, seg['freq'], seg['name'])

        # Frequency accuracy
        verdict(abs(r['freq_error_hz']) < 2.0, "Frequency accuracy",
                f"{r['dominant_freq']:.1f} Hz ({r['freq_error_hz']:+.2f})", "Hz")

        # Level
        exp_db, clips = expected_output.get(idx, (None, False))
        if exp_db is not None:
            if clips:
                # Clipped signals: peak should be near 0 dBFS
                verdict(r['peak_dbfs'] > -3.0, "Peak level (clipped)",
                        f"{r['peak_dbfs']:.1f}", "dBFS")
            else:
                level_err = abs(r['peak_dbfs'] - exp_db)
                verdict(level_err < 3.0, "Peak level",
                        f"{r['peak_dbfs']:.1f} (exp {exp_db:.1f})", "dBFS")

        # THD
        if clips:
            # Clipped: high THD expected (harmonics from clipping)
            print_result("THD (clipped, informational)",
                         f"{r['thd_pct']:.1f}", "%")
        else:
            verdict(r['thd_pct'] < 2.0, "THD",
                    f"{r['thd_pct']:.2f}", "%")

        # Noise floor
        verdict(r['noise_floor_db'] < -50, "Noise floor",
                f"{r['noise_floor_db']:.1f}", "dB", warn=True)

    # Phase 6: 440 Hz
    seg = segments[6]
    print_header(f"Phase 6: {seg['name']}")
    if len(seg['data']) < sr // 2:
        print("  SKIPPED (insufficient data — recording too short)")
    else:
        r = analyze_sine(seg['data'], sr, seg['freq'], seg['name'])
        verdict(abs(r['freq_error_hz']) < 2.0, "Frequency accuracy",
                f"{r['dominant_freq']:.1f} Hz ({r['freq_error_hz']:+.2f})", "Hz")
        verdict(r['thd_pct'] < 2.0, "THD", f"{r['thd_pct']:.2f}", "%")

    # Phase 7: SWEEP
    seg = segments[7]
    print_header(f"Phase 7: {seg['name']}")
    if len(seg['data']) < sr:
        print("  SKIPPED (insufficient data — recording too short)")
        r = None
    else:
        r = analyze_sweep(seg['data'], sr, seg['name'])
    if r is not None:
        print_result("Reference power", f"{r['ref_power_db']:.1f}", "dB")
        verdict(r['bandwidth_m3db'] > 15000, "-3 dB bandwidth",
                f"{r['bandwidth_m3db']:.0f}", "Hz")
        verdict(r['passband_ripple_db'] < 3.0, "Passband ripple (200-15k)",
                f"{r['passband_ripple_db']:.1f}", "dB")

    # Phase 8: SQUARE
    seg = segments[8]
    print_header(f"Phase 8: {seg['name']}")
    if len(seg['data']) < sr // 2:
        print("  SKIPPED (insufficient data — recording too short)")
        r = None
    else:
        r = analyze_square(seg['data'], sr, seg['name'])
    if r is None:
        pass
    else:
      print_result("Fundamental", f"{r['fund_mag_db']:.1f}", "dB")
      # Check odd harmonics present, even harmonics absent
      for h, freq, mag_db_val in r['odd_harmonics'][:5]:
        relative = mag_db_val - r['fund_mag_db']
        # Ideal: 1/h amplitude = -20*log10(h)
        ideal = -20 * np.log10(h)
        err = abs(relative - ideal)
        verdict(err < 6, f"Harmonic {h} ({freq} Hz)",
                f"{relative:.1f} dB (ideal {ideal:.1f})", "", warn=True)

    # Phase 9: IMD
    seg = segments[9]
    print_header(f"Phase 9: {seg['name']}")
    if len(seg['data']) < sr // 2:
        print("  SKIPPED (insufficient data — recording too short)")
        r = None
    else:
        r = analyze_imd(seg['data'], sr, seg['name'])
    if r is None:
        pass
    else:
      for tone_name, level in r['tones'].items():
        if level is None:
            print_result(f"  {tone_name}", "N/A (above Nyquist)", "")
        else:
            print_result(f"  {tone_name}", f"{level:.1f}", "dB")
      # Check IMD product at 1 kHz is suppressed
      if r['tones'].get('IMD 1kHz') is not None and r['tones'].get('19kHz') is not None:
        imd_suppression = r['tones']['19kHz'] - r['tones']['IMD 1kHz']
        verdict(imd_suppression > 20, "IMD suppression (1 kHz product)",
                f"{imd_suppression:.1f}", "dB")

    # Phase 10: IMPULSE
    seg = segments[10]
    print_header(f"Phase 10: {seg['name']}")
    if len(seg['data']) < sr // 2:
        print("  SKIPPED (insufficient data — recording too short)")
        r = None
    else:
        r = analyze_impulse(seg['data'], sr, seg['name'])
    if r is None:
        pass
    elif 'error' in r:
        print(f"  ERROR: {r['error']}")
        fail_count += 1
    else:
        verdict(abs(r['measured_rate_hz'] - 200) < 10, "Impulse rate",
                f"{r['measured_rate_hz']:.1f}", "Hz")
        verdict(r['spacing_jitter_ms'] < 0.5, "Spacing jitter",
                f"{r['spacing_jitter_ms']:.3f}", "ms")
        print_result("Impulse width (-10%)",
                     f"{r['impulse_width_samples']}", "samples")
        print_result("Impulses found", f"{r['n_impulses']}", "")

    # ── Summary ────────────────────────────────────────────────────────
    print_header("SUMMARY")
    total = pass_count + fail_count + warn_count
    print(f"  PASS: {pass_count}/{total}")
    print(f"  WARN: {warn_count}/{total}")
    print(f"  FAIL: {fail_count}/{total}")
    if fail_count == 0:
        print("\n  Audio pipeline looks healthy!")
    else:
        print(f"\n  {fail_count} issue(s) detected — see FAIL results above.")


if __name__ == '__main__':
    main()
