// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// pio_spi_oled //
// ------------ //

#define pio_spi_oled_wrap_target 0
#define pio_spi_oled_wrap 1
#define pio_spi_oled_pio_version 0

static const uint16_t pio_spi_oled_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1         side 0
    0xb042, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_spi_oled_program = {
    .instructions = pio_spi_oled_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = pio_spi_oled_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pio_spi_oled_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_spi_oled_wrap_target, offset + pio_spi_oled_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

